# Generated by Django 4.2 on 2026-09-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
